services:
  - type: web
    name: asistentruck-bodega-control
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
